### ISSUE TITLE
Interval crash related to Cog flying away

### ISSUE THREAD

**Issue by Benjamin8693** [Toontown-Offline-Issue-Tracker/issues#14]
Skimmed this log, but the client seemed to crash due to something going wrong in an interval where a Cog flies away.
[ttoff-200622_004111-1.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4878375/ttoff-200622_004111-1.log)

**Comment by ooowoothevirtualhowler** [comment]
Looks like the easter egg cutscene again. It still crashes everyone in the zone if you go sad and you're the intended target of it in the current build of the game. Also DelayDelete can't save the person who went sad because it reloads the zone, thus disabling the fountain and deleting all the Actors in that cutscene so that's gotta be thought about.
