### ISSUE TITLE
"Meet Here" Easter Egg Toons sometimes don't clean up properly

### ISSUE THREAD

**Issue by Benjamin8693** [Toontown-Offline-Issue-Tracker/issues#4]
"When doing meet here, and greening the toon,  if done too early, they never leave or respond, if doing meet here again, another toon will appear. If you green that toon after waiting, it will send you to ddl secret, but the first toon, which was stuck, follows or is there as well."

![](https://cdn.discordapp.com/attachments/688506501245042828/707338104041635910/crazycurlydrive.PNG)

**Comment by Benjamin8693** [comment]
May have been fixed by a recent commit from Owo. Not sure, will wait until he properly joins this repo as a contributor so I can ping him about it.

**Comment by Benjamin8693** [comment]
@ooowoothevirtualhowler

**Comment by ooowoothevirtualhowler** [comment]
Ya I think it's probably fixed. Used to happen a lot more in much older versions. I'm guessing it probably happened because of method redundancy because I couldn't replicate it either. Either that or it was because of using the locking system to lock toons down. The teleport method didn't really like the locking method being placed after the teleport in the interval.
